### ISSUE TITLE
DeepDetect builds with `TENSORRT_OSS` do require CUDA 10.2

### ISSUE THREAD

**Issue by beniz** [jolibrain/deepdetect#811]
Otherwise the build error is as follows: 
```
deepdetect/build/tensorrt-oss/src/tensorrt-oss/samples/common/sampleDevice.h:189:56: error: ‘cudaStreamCaptureModeGlobal’ was not declared in this scope
         cudaCheck(cudaStreamBeginCapture(stream.get(), cudaStreamCaptureModeGlobal));
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
deepdetect/build/tensorrt-oss/src/tensorrt-oss/samples/common/sampleDevice.h:189:56: note: suggested alternative: ‘cudaStreamCaptureStatusNone’
         cudaCheck(cudaStreamBeginCapture(stream.get(), cudaStreamCaptureModeGlobal));
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                        cudaStreamCaptureStatusNone
```

FTR this also appears here: https://github.com/triton-inference-server/server/issues/635

Using CUDA 10.2 fixes the issue. A check for CUDA 10.2 is probably needed in the `CMakeFile` to catch the issue much earlier.

**Comment by YaYaB** [comment]
According to the issue on triton-infenrence-server it should work with cuda 10.1 no?

**Comment by beniz** [comment]
dk, 10.1 is deprecated for us.
